package model.move;

public enum MoveGeneratingStyle {
    ALL_TYPE_MOVES_PIECE_BY_PIECE,
    TYPE_BY_TYPE_MOVES_PIECE_BY_PIECE,
    DIRECTION_BY_DIRECTION_MOVES_PIECE_BY_PIECE,
    ALL_TYPE_MOVES_DIRECTION_BY_DIRECTION,
    TYPE_BY_TYPE_MOVES_DIRECTION_BY_DIRECTION,
    DIRECTION_BY_DIRECTION_MOVES_TYPE_BY_TYPE
}
